# ============================================
# Cloud Build configuration for Cloud Run
# ============================================
#
# To deploy manually:
#   gcloud builds submit --config cloudbuild.yaml
#
# Or set up a trigger in Cloud Build for auto-deploy on push
#

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/artreal-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/artreal-backend:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/artreal-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/artreal-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'artreal-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/artreal-backend:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'  # Change to your preferred region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'DEBUG=False'

images:
  - 'gcr.io/$PROJECT_ID/artreal-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/artreal-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
